In [1]:
import numpy as np

#### Create a matrix

In [3]:
A = np.array([[5,6,1],[7,8,9],[1,0,2],[4,3,6]])

In [4]:
A

array([[5, 6, 1],
       [7, 8, 9],
       [1, 0, 2],
       [4, 3, 6]])

In [6]:
print(A)

[[5 6 1]
 [7 8 9]
 [1 0 2]
 [4 3 6]]


In [7]:
# data type of variables
A.dtype

dtype('int64')

In [8]:
# number of dimensions
A.ndim

2

In [9]:
# total number of elements
A.size

12

In [10]:
# order of matrix m x n (m-rows, n-columns)
A.shape

(4, 3)

In [11]:
A.shape[0]

4

In [12]:
A.shape[1]

3

In [15]:
A = np.array([[5,6,1],[7,8,9],[1,0,2],[4,3,6]], dtype=np.int16)

In [16]:
A

array([[5, 6, 1],
       [7, 8, 9],
       [1, 0, 2],
       [4, 3, 6]], dtype=int16)

In [17]:
A1 = np.array([[5,6,1],[7,8,9],[1,0,2],[4,3,6]], dtype=np.float32)

In [18]:
A1

array([[5., 6., 1.],
       [7., 8., 9.],
       [1., 0., 2.],
       [4., 3., 6.]], dtype=float32)

#### Create a matrix from vector

In [20]:
v1 = np.array([5,7,6,12,87,43,22,5,64])

In [21]:
v1.shape

(9,)

In [22]:
v1.reshape(3,3)

array([[ 5,  7,  6],
       [12, 87, 43],
       [22,  5, 64]])

In [23]:
B = v1.reshape(3,3)
print(B)

[[ 5  7  6]
 [12 87 43]
 [22  5 64]]


In [24]:
v1.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [25]:
np.reshape(v1, (3,3))

array([[ 5,  7,  6],
       [12, 87, 43],
       [22,  5, 64]])

In [26]:
v1.reshape(9,1)

array([[ 5],
       [ 7],
       [ 6],
       [12],
       [87],
       [43],
       [22],
       [ 5],
       [64]])

In [27]:
v1.reshape(1,9)

array([[ 5,  7,  6, 12, 87, 43, 22,  5, 64]])

In [31]:
Z = np.zeros((3,4))

In [32]:
# Zero matrix
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
U = np.ones((4,2))

In [36]:
# Unit Matrix
U

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
Z = np.zeros((3,4), dtype=np.int8)

In [38]:
Z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [39]:
C = np.zeros((3,3), dtype=np.bool_)

In [40]:
C

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

#### Matrix Iterations

In [42]:
A

array([[5, 6, 1],
       [7, 8, 9],
       [1, 0, 2],
       [4, 3, 6]], dtype=int16)

In [43]:
A[0]

array([5, 6, 1], dtype=int16)

In [44]:
for row in A:
    print(row)

[5 6 1]
[7 8 9]
[1 0 2]
[4 3 6]


In [45]:
A[2][1]

0

In [48]:
for row in A:
    for value in row:
        print(value, end=' ')
    print()

5 6 1 
7 8 9 
1 0 2 
4 3 6 


In [49]:
# Read the dimensions of matrix from user and intialize it
# by user input 

In [53]:
rows = int(input('Enter number of rows   : '))
cols = int(input('Enter number of columns: '))
M = np.zeros((rows, cols), dtype=np.int16)
for r in range(rows):
    for c in range(cols):
        num = int(input('Enter a number: '))
        M[r][c] = num
        
print('Matrix:\n', M)

Enter number of rows   : 2
Enter number of columns: 2
Enter a number: 34
Enter a number: 55
Enter a number: 66
Enter a number: 33
Matrix:
 [[34 55]
 [66 33]]


#### Scalar operations

In [55]:
A

array([[5, 6, 1],
       [7, 8, 9],
       [1, 0, 2],
       [4, 3, 6]], dtype=int16)

In [56]:
A + 5

array([[10, 11,  6],
       [12, 13, 14],
       [ 6,  5,  7],
       [ 9,  8, 11]], dtype=int16)

In [57]:
A * 3

array([[15, 18,  3],
       [21, 24, 27],
       [ 3,  0,  6],
       [12,  9, 18]], dtype=int16)

In [58]:
A - 2

array([[ 3,  4, -1],
       [ 5,  6,  7],
       [-1, -2,  0],
       [ 2,  1,  4]], dtype=int16)

In [59]:
abs(A - 2)

array([[3, 4, 1],
       [5, 6, 7],
       [1, 2, 0],
       [2, 1, 4]], dtype=int16)

In [60]:
A / 2

array([[2.5, 3. , 0.5],
       [3.5, 4. , 4.5],
       [0.5, 0. , 1. ],
       [2. , 1.5, 3. ]])

In [61]:
A % 2

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 1, 0]], dtype=int16)

In [62]:
A > 5

array([[False,  True, False],
       [ True,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [63]:
A <= 5

array([[ True, False,  True],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True, False]])

In [64]:
B

array([[ 5,  7,  6],
       [12, 87, 43],
       [22,  5, 64]])

#### Matrix Operations

In [74]:
D = np.empty((4,3), dtype=np.int16)

In [82]:
np.random.randint(2,56)

2

In [88]:
# create a matrix with random values
M = np.zeros((4,3), dtype=np.int16)
for r in range(4):
    for c in range(3):
        M[r][c] = np.random.randint(2,17)

In [89]:
M

array([[11,  7, 16],
       [12,  3, 16],
       [ 2, 16,  3],
       [ 3,  7,  2]], dtype=int16)

In [90]:
N = A + M

In [91]:
N

array([[16, 13, 17],
       [19, 11, 25],
       [ 3, 16,  5],
       [ 7, 10,  8]], dtype=int16)

In [92]:
S = A - M

In [93]:
S

array([[ -6,  -1, -15],
       [ -5,   5,  -7],
       [ -1, -16,  -1],
       [  1,  -4,   4]], dtype=int16)

In [99]:
(A + M) * 2

array([[32, 26, 34],
       [38, 22, 50],
       [ 6, 32, 10],
       [14, 20, 16]], dtype=int16)

In [100]:
2*A + 2*M

array([[32, 26, 34],
       [38, 22, 50],
       [ 6, 32, 10],
       [14, 20, 16]], dtype=int16)

In [101]:
k=2
l=3
(k+l) * A

array([[25, 30,  5],
       [35, 40, 45],
       [ 5,  0, 10],
       [20, 15, 30]], dtype=int16)

In [102]:
k*A + l*A 

array([[25, 30,  5],
       [35, 40, 45],
       [ 5,  0, 10],
       [20, 15, 30]], dtype=int16)

In [105]:
(k*l)*A, k*(l*A), l*(k*A)

(array([[30, 36,  6],
        [42, 48, 54],
        [ 6,  0, 12],
        [24, 18, 36]], dtype=int16),
 array([[30, 36,  6],
        [42, 48, 54],
        [ 6,  0, 12],
        [24, 18, 36]], dtype=int16),
 array([[30, 36,  6],
        [42, 48, 54],
        [ 6,  0, 12],
        [24, 18, 36]], dtype=int16))

In [110]:
(-k)*A, -(k*A), k*(-A)

(array([[-10, -12,  -2],
        [-14, -16, -18],
        [ -2,   0,  -4],
        [ -8,  -6, -12]], dtype=int16),
 array([[-10, -12,  -2],
        [-14, -16, -18],
        [ -2,   0,  -4],
        [ -8,  -6, -12]], dtype=int16),
 array([[-10, -12,  -2],
        [-14, -16, -18],
        [ -2,   0,  -4],
        [ -8,  -6, -12]], dtype=int16))

In [112]:
1 * A, A

(array([[5, 6, 1],
        [7, 8, 9],
        [1, 0, 2],
        [4, 3, 6]], dtype=int16),
 array([[5, 6, 1],
        [7, 8, 9],
        [1, 0, 2],
        [4, 3, 6]], dtype=int16))

In [114]:
-1 * A, -A

(array([[-5, -6, -1],
        [-7, -8, -9],
        [-1,  0, -2],
        [-4, -3, -6]], dtype=int16),
 array([[-5, -6, -1],
        [-7, -8, -9],
        [-1,  0, -2],
        [-4, -3, -6]], dtype=int16))

In [116]:
M.shape

(4, 3)

In [117]:
A.shape

(4, 3)

In [119]:
A, M, A * M

(array([[5, 6, 1],
        [7, 8, 9],
        [1, 0, 2],
        [4, 3, 6]], dtype=int16),
 array([[11,  7, 16],
        [12,  3, 16],
        [ 2, 16,  3],
        [ 3,  7,  2]], dtype=int16),
 array([[ 55,  42,  16],
        [ 84,  24, 144],
        [  2,   0,   6],
        [ 12,  21,  12]], dtype=int16))

In [121]:
P = np.array([[3,5,4],[0,7,1]])

In [122]:
Q = np.array([[4,5],[7,2],[1,2]])

In [123]:
P, Q

(array([[3, 5, 4],
        [0, 7, 1]]),
 array([[4, 5],
        [7, 2],
        [1, 2]]))

In [124]:
# 51, 33, 50, 16

In [125]:
np.matmul(P, Q)

array([[51, 33],
       [50, 16]])

In [126]:
P @ Q

array([[51, 33],
       [50, 16]])

In [128]:
A @ B

array([[119, 562, 352],
       [329, 790, 962],
       [ 49,  17, 134],
       [188, 319, 537]])

In [131]:
A @ B, B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [142]:
R1 = np.zeros((3,3), dtype=np.int32)
R2 = np.zeros((3,3), dtype=np.int32)
R3 = np.zeros((3,3), dtype=np.int32)
for r in range(3):
    for c in range(3):
        R1[r][c] = np.random.randint(10,25)
        R2[r][c] = np.random.randint(10,25)
        R3[r][c] = np.random.randint(10,25)

In [143]:
R1, R2, R3

(array([[15, 20, 14],
        [24, 23, 12],
        [18, 13, 14]], dtype=int32),
 array([[21, 10, 17],
        [11, 20, 18],
        [21, 21, 20]], dtype=int32),
 array([[19, 12, 21],
        [10, 18, 14],
        [19, 11, 22]], dtype=int32))

In [144]:
R1 @ R2, R2 @ R1

(array([[ 829,  844,  895],
        [1009,  952, 1062],
        [ 815,  734,  820]], dtype=int32),
 array([[ 861,  871,  652],
        [ 969,  914,  646],
        [1179, 1163,  826]], dtype=int32))

In [145]:
R1 @ (R2 @ R3), (R1 @ R2) @ R3

(array([[41196, 34985, 48915],
        [48869, 40926, 57881],
        [38405, 32012, 45431]], dtype=int32),
 array([[41196, 34985, 48915],
        [48869, 40926, 57881],
        [38405, 32012, 45431]], dtype=int32))

In [148]:
(R1 + R2) @ R3,      R1 @ R3 + R2 @ R3

(array([[1573, 1313, 1858],
        [1665, 1524, 1997],
        [1727, 1454, 2043]], dtype=int32),
 array([[1573, 1313, 1858],
        [1665, 1524, 1997],
        [1727, 1454, 2043]], dtype=int32))

##### Transpose

In [155]:
R4 = A.transpose()

In [156]:
R4

array([[5, 7, 1, 4],
       [6, 8, 0, 3],
       [1, 9, 2, 6]], dtype=int16)

In [157]:
A.shape, R4.shape

((4, 3), (3, 4))

In [158]:
A, R4

(array([[5, 6, 1],
        [7, 8, 9],
        [1, 0, 2],
        [4, 3, 6]], dtype=int16),
 array([[5, 7, 1, 4],
        [6, 8, 0, 3],
        [1, 9, 2, 6]], dtype=int16))

In [159]:
np.transpose(A)

array([[5, 7, 1, 4],
       [6, 8, 0, 3],
       [1, 9, 2, 6]], dtype=int16)

In [161]:
A.transpose().transpose(), A

(array([[5, 6, 1],
        [7, 8, 9],
        [1, 0, 2],
        [4, 3, 6]], dtype=int16),
 array([[5, 6, 1],
        [7, 8, 9],
        [1, 0, 2],
        [4, 3, 6]], dtype=int16))

In [168]:
(R1 + R2).transpose(), R1.transpose() + R2.transpose()

(array([[36, 35, 39],
        [30, 43, 34],
        [31, 30, 34]], dtype=int32),
 array([[36, 35, 39],
        [30, 43, 34],
        [31, 30, 34]], dtype=int32))

In [170]:
2 * R1.transpose(), (2 * R1).transpose()

(array([[30, 48, 36],
        [40, 46, 26],
        [28, 24, 28]], dtype=int32),
 array([[30, 48, 36],
        [40, 46, 26],
        [28, 24, 28]], dtype=int32))

In [174]:
(R1 @ R2).transpose(), R2.transpose() @ R1.transpose()

(array([[ 829, 1009,  815],
        [ 844,  952,  734],
        [ 895, 1062,  820]], dtype=int32),
 array([[ 829, 1009,  815],
        [ 844,  952,  734],
        [ 895, 1062,  820]], dtype=int32))

##### trace

In [175]:
R1

array([[15, 20, 14],
       [24, 23, 12],
       [18, 13, 14]], dtype=int32)

In [176]:
R1.trace()

52

In [177]:
A.trace()

15

In [178]:
A

array([[5, 6, 1],
       [7, 8, 9],
       [1, 0, 2],
       [4, 3, 6]], dtype=int16)

In [183]:
for r in range(3):
    for c in range(3):
        if r == c:
            print(R1[r][c], end=' ')

15 23 14 

In [182]:
R1.diagonal()

array([15, 23, 14], dtype=int32)

In [184]:
for r in range(R1.shape[0]):
    for c in range(R1.shape[1]):
        if r == c:
            print(R1[r][c], end=' ')

15 23 14 

In [185]:
for r in range(A.shape[0]):
    for c in range(A.shape[1]):
        if r == c:
            print(A[r][c], end=' ')

5 8 2 

In [186]:
R1.trace(), R2.trace()

(52, 61)

In [188]:
(R1 @ R2).trace()

2601

In [189]:
(R2 @ R1).trace()

2601

In [193]:
R1.trace(), R1.transpose().trace()

(52, 52)

In [195]:
(R1 * 2).trace(),  R1.trace() * 2

(104, 104)

In [197]:
R1.trace() + R2.trace(),  (R1 + R2).trace()

(113, 113)

##### Determinant

In [199]:
R1

array([[15, 20, 14],
       [24, 23, 12],
       [18, 13, 14]], dtype=int32)

In [200]:
np.linalg.det(R1)

-1337.9999999999995

In [201]:
np.linalg.det(R2)

-1171.000000000001

In [202]:
np.linalg.det(R3)

277.9999999999997

##### Inverse of matrix

In [204]:
R1

array([[15, 20, 14],
       [24, 23, 12],
       [18, 13, 14]], dtype=int32)

In [205]:
np.linalg.inv(R1)

array([[-0.12406577,  0.07324365,  0.0612855 ],
       [ 0.0896861 ,  0.03139013, -0.11659193],
       [ 0.07623318, -0.12331839,  0.10089686]])

In [206]:
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

##### Rank of matrix

In [208]:
R1

array([[15, 20, 14],
       [24, 23, 12],
       [18, 13, 14]], dtype=int32)

In [209]:
np.linalg.matrix_rank(R1)

3

In [221]:
R5 = np.array([[1,2,3],[1,2,3],[2,3,4]])
R5

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [222]:
np.linalg.matrix_rank(R5)

2

In [223]:
R5 = np.array([[1,2,3],[1,2,3],[1,2,3]])
np.linalg.matrix_rank(R5)

1

In [226]:
R5 = np.array([[1,2,5],[1,6,7],[1,2,8]])
np.linalg.matrix_rank(R5)

3

In [227]:
R5

array([[1, 2, 5],
       [1, 6, 7],
       [1, 2, 8]])

#### Types of Matrices

##### row matrix

In [230]:
X = np.array([[5,4,6,7,8]])

In [231]:
X

array([[5, 4, 6, 7, 8]])

In [232]:
X.ndim

2

In [233]:
X.shape

(1, 5)

##### column matrix

In [235]:
X = np.array([[5],[4],[6],[7],[8]])

In [236]:
X

array([[5],
       [4],
       [6],
       [7],
       [8]])

In [237]:
X.shape

(5, 1)

In [238]:
X.reshape(1,5)

array([[5, 4, 6, 7, 8]])

In [239]:
v = X.reshape(5)

In [240]:
v

array([5, 4, 6, 7, 8])

In [241]:
v.shape

(5,)

In [242]:
X = np.array([[5,4,6,7,8,1]])

In [243]:
X.shape

(1, 6)

In [244]:
X.reshape(-1, 2)

array([[5, 4],
       [6, 7],
       [8, 1]])

In [245]:
X.reshape(2, -1)

array([[5, 4, 6],
       [7, 8, 1]])

In [246]:
X.flatten()

array([5, 4, 6, 7, 8, 1])

In [247]:
X

array([[5, 4, 6, 7, 8, 1]])

In [248]:
X.transpose()

array([[5],
       [4],
       [6],
       [7],
       [8],
       [1]])

##### Square matrix

In [252]:
S1 = np.zeros((4,4))
S2 = np.zeros((3,4))

In [253]:
S1, S2

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [254]:
S1.shape

(4, 4)

In [255]:
def is_square_matrix(M):
    if M.shape[0] == M.shape[1]:
        return True
    else:
        return False

In [256]:
is_square_matrix(R1)

True

In [257]:
is_square_matrix(A)

False

In [258]:
def is_rectangular_matrix(M):
    if M.shape[0] != M.shape[1]:
        return True
    else:
        return False

In [259]:
is_rectangular_matrix(A)

True

In [260]:
is_rectangular_matrix(R1)

False

#### Diagonal Matrix

In [264]:
D = np.zeros((4,4))

In [266]:
for r in range(4):
    for c in range(4):
        if r == c:
            D[r][c] = np.random.randint(1,10)

In [267]:
D

array([[6., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 8.]])

In [269]:
def create_diagonal_matrix(shape):
    D = np.zeros((shape, shape))
    for r in range(shape):
        for c in range(shape):
            if r == c:
                D[r][c] = np.random.randint(1,10)
    return D

In [274]:
create_diagonal_matrix(6)

array([[5., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]])

#### Identity matrix

In [280]:
# create identity matrix with random values
M = np.zeros((4,4), dtype=np.int16)
for r in range(4):
    for c in range(4):
        if r == c:
            M[r][c] = 1
        else:
            M[r][c] = np.random.randint(2,17)

In [281]:
M

array([[ 1,  7,  4,  2],
       [ 9,  1, 10,  6],
       [ 3, 14,  1,  9],
       [15,  3,  2,  1]], dtype=int16)

In [282]:
def create_identity_matrix(shape):
    M = np.zeros((shape, shape), dtype=np.int16)
    for r in range(shape):
        for c in range(shape):
            if r == c:
                M[r][c] = 1
            else:
                M[r][c] = np.random.randint(2,17)
    return M

In [283]:
create_identity_matrix(3)

array([[ 1, 14, 14],
       [11,  1, 14],
       [ 3, 11,  1]], dtype=int16)

In [294]:
R1.diagonal()

array([15, 23, 14], dtype=int32)

In [296]:
# write a function to check identity matrix or not
def is_identity_matrix(M):
    diag = M.diagonal()
    for n in diag:
        if n != 1:
            return False
    return True

In [299]:
D = create_identity_matrix(3)

In [301]:
is_identity_matrix(D)

True

In [302]:
is_identity_matrix(A)

False

#### Symmetric Matrix

In [305]:
M = np.zeros((4,4), dtype=np.int16)

In [312]:
for r in range(4):
    for c in range(r,4):
        M[r][c] = np.random.randint(2,15)
        M[c][r] = M[r][c]

In [325]:
M

array([[ 5,  2,  7, 12],
       [ 2,  4, 13,  5],
       [ 7, 13,  9,  2],
       [12,  5,  2, 14]], dtype=int16)

In [316]:
def create_symmetric_matrix(shape):
    M = np.zeros((shape,shape), dtype=np.int16)
    for r in range(shape):
        for c in range(r,shape):
            M[r][c] = np.random.randint(2,15)
            M[c][r] = M[r][c]
    return M

In [326]:
N = create_symmetric_matrix(5)

In [327]:
N

array([[ 5,  4, 11, 13,  6],
       [ 4,  4, 11, 11,  9],
       [11, 11,  2,  5,  6],
       [13, 11,  5, 14,  2],
       [ 6,  9,  6,  2,  2]], dtype=int16)

In [328]:
N, N.transpose()

(array([[ 5,  4, 11, 13,  6],
        [ 4,  4, 11, 11,  9],
        [11, 11,  2,  5,  6],
        [13, 11,  5, 14,  2],
        [ 6,  9,  6,  2,  2]], dtype=int16),
 array([[ 5,  4, 11, 13,  6],
        [ 4,  4, 11, 11,  9],
        [11, 11,  2,  5,  6],
        [13, 11,  5, 14,  2],
        [ 6,  9,  6,  2,  2]], dtype=int16))

In [331]:
all([1,1,1,0,1])

False

In [335]:
all((M == M.transpose()).flatten())

True

In [339]:
def is_symmetric_matrix(M):
    if M.shape[0] == M.shape[1]:
        return all((M == M.transpose()).flatten())
    return False

In [343]:
is_symmetric_matrix(N)

True

In [344]:
is_symmetric_matrix(R1)

False

#### Skew-symmetric matrix

In [346]:
def create_skew_symmetric_matrix(shape):
    M = np.zeros((shape,shape), dtype=np.int16)
    for r in range(shape):
        for c in range(r,shape):
            if r != c:
                M[r][c] = np.random.randint(2,15)
                M[c][r] = -M[r][c]
    return M

In [348]:
Q = create_skew_symmetric_matrix(5)

In [349]:
Q

array([[  0,   5,   2,   4,  12],
       [ -5,   0,   8,   2,  10],
       [ -2,  -8,   0,  11,  10],
       [ -4,  -2, -11,   0,  10],
       [-12, -10, -10, -10,   0]], dtype=int16)

In [350]:
Q, -Q.transpose()

(array([[  0,   5,   2,   4,  12],
        [ -5,   0,   8,   2,  10],
        [ -2,  -8,   0,  11,  10],
        [ -4,  -2, -11,   0,  10],
        [-12, -10, -10, -10,   0]], dtype=int16),
 array([[  0,   5,   2,   4,  12],
        [ -5,   0,   8,   2,  10],
        [ -2,  -8,   0,  11,  10],
        [ -4,  -2, -11,   0,  10],
        [-12, -10, -10, -10,   0]], dtype=int16))

In [351]:
def is_skew_symmetric_matrix(M):
    if M.shape[0] == M.shape[1]:
        return all((M == -M.transpose()).flatten())
    return False

In [352]:
is_skew_symmetric_matrix(Q)

True

In [353]:
is_skew_symmetric_matrix(M)

False

#### Orthonormal Matrix

In [355]:
O = np.array([[1/np.sqrt(2),1/np.sqrt(2)],
              [-1/np.sqrt(2), 1/np.sqrt(2)]])

In [356]:
O

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [382]:
np.linalg.inv(O), O.transpose()

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [383]:
round(np.linalg.det(O),0) == 1

True

In [388]:
v = 1.67
v == 1.67

True

In [386]:
np.linalg.inv(O) == O.transpose()

array([[False, False],
       [False, False]])

In [376]:
def is_orthonormal_matrix(M):
    if M.shape[0] == M.shape[1]:
        return all((np.linalg.inv(M) == M.transpose()).flatten()) and round(np.linalg.det(M),0) == 1
    return False

In [377]:
is_orthonormal_matrix(O)

False

In [378]:
O

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

#### Eigen Values

In [391]:
R1

array([[15, 20, 14],
       [24, 23, 12],
       [18, 13, 14]], dtype=int32)

In [394]:
w, v = np.linalg.eig(R1)

In [395]:
### Eigen Value
w

array([51.71237279, -4.94485691,  5.23248412])

In [396]:
### Eigen vector
v

array([[ 0.55360065,  0.77377636,  0.02321882],
       [ 0.66965058, -0.49458138, -0.5808934 ],
       [ 0.49507013, -0.39580223,  0.81364841]])

In [399]:
v * w

array([[28.62800299, -3.82621338,  0.12149213],
       [34.62922029,  2.44563416, -3.0395155 ],
       [25.60125089,  1.95718537,  4.25740241]])

In [403]:
v @ np.diag(w) @ v.transpose()

array([[12.89066839, 20.99255865, 15.78614468],
       [20.99255865, 23.74554672, 13.70280802],
       [15.78614468, 13.70280802, 15.36378488]])

In [404]:
# Create a NumPy array containing the eigenvalues
eigenvalues = np.array([1, 2, 3])

# Create a NumPy array containing the eigenvectors
eigenvectors = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

# Calculate the original matrix
original_matrix = eigenvectors @ np.diag(eigenvalues) 
@ eigenvectors.T

# Print the original matrix
print(original_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
